name = "infinite-email"
main = "src/index.ts"
compatibility_date = "2026-02-28"

[vars]
# DOMAIN = "example.com"
# ADMIN_TOKEN = "your-secret-token"

[[d1_databases]]
binding = "DB"
database_name = "infinite_email"
database_id = "b7cb4c31-0fe1-4ea6-a29d-9471e2f58907"
migrations_dir = "src/migrations"
